# Generated by Django 2.0.10 on 2021-05-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circles', '0003_auto_20210509_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='remainig_invitations',
            new_name='remaining_invitations',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='used_invitation',
            new_name='used_invitations',
        ),
    ]
